# Generated by Django 4.2.2 on 2023-07-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Title', models.TextField(max_length=100)),
                ('Countdown', models.DurationField()),
                ('Onsite', models.BooleanField()),
                ('OffSite', models.BooleanField()),
                ('Files', models.FileField(upload_to='uploads/% Y/% m/% d/')),
                ('JobDuration', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
