# Generated by Django 4.2.2 on 2023-07-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='OffSite',
        ),
        migrations.AlterField(
            model_name='upload',
            name='Countdown',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Files',
            field=models.FileField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Onsite',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Title',
            field=models.CharField(max_length=50),
        ),
    ]
