# Generated by Django 4.2.2 on 2023-07-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_upload_offsite_alter_upload_countdown_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-created_at']},
        ),
    ]
