# Generated by Django 4.2.2 on 2023-07-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_upload_countdown_remove_upload_jobduration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='Files',
        ),
    ]
