# Generated by Django 4.2.2 on 2023-07-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_upload_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='Onsite',
        ),
        migrations.AddField(
            model_name='upload',
            name='Type',
            field=models.CharField(blank=True, choices=[('ON-SITE', 'ON-SITE'), ('REMOTE', 'REMOTE'), ('HYBRID', 'HYBRID')], max_length=200, null=True),
        ),
    ]
