# Generated by Django 4.2.2 on 2023-07-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_upload_onsite_upload_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='Duration',
            field=models.TextField(choices=[('Less than a week', 'Less than a week'), ('1 to 4 weeks', '1 to 4 weeks'), ('1 to 3 months', '1 to 3 months'), ('More than 3 months', 'More than 3 months')], null=True),
        ),
    ]
