# Generated by Django 4.2.2 on 2023-07-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_jobpost_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='Type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(default='9crlus'),
        ),
    ]
