# Generated by Django 4.2.2 on 2023-07-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_rename_category_jobpost_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='jobs',
            new_name='job',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(default='zetfpr'),
        ),
    ]
